site_name: Documentation Template
repo_url: https://github.com/ISAsxm/Documentation_Template
edit_uri: blob/main/docs/

copyright: Copyright &copy; 2022 - ISAsxm 

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.svg
  favicon: images/favicon.svg
  icon:
    repo: fontawesome/brands/github
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - toc.follow
    - navigation.instant
    - navigation.top
    - search.suggest
    - content.code.annotate


markdown_extensions:
  - toc:
      permalink: '#'
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.progressbar

extra:
  # homepage: index.en/
  alternate:
    - name: English
      link: ""
      lang: en
    - name: Français
      link: index.fr/
      lang: fr
  version:
    provider: mike
    default: latest

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang: 
        - en
        - fr
  - i18n:
      languages:
        en: "English"
        fr: "Français"
      default_language: 'en'
      no_translation:
        en: "This page is not translated into English."
        fr: "Cette page n'est pas traduite en français."
  - glightbox

nav:
  - index.md
  - index.fr.md
  - about.en.md
  - about.fr.md